services:
    app:
        build: .
        image: michaelrushton/${COMPOSE_PROJECT_NAME}/app
        container_name: ${COMPOSE_PROJECT_NAME}-app
        user: ${uid:-www-data}:${gid:-www-data}
        depends_on:
            server:
                condition: service_started
            db:
                condition: service_healthy
        volumes:
            - ..:/var/www/html
    server:
        image: nginx:alpine-slim
        container_name: ${COMPOSE_PROJECT_NAME}-server
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../public:/var/www/html/public
    db:
        image: postgres:17-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-db
        ports:
            - ${DB_PORT:-5432}:5432
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: trust
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${DB_DATABASE}"]
            interval: 1s
        volumes:
            - db-data:/var/lib/postgresql/data
    db-testing:
        image: postgres:17-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-db-testing
        ports:
            - ${DB_TESTING_PORT:-5433}:5432
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - db-testing-data:/var/lib/postgresql/data
    mailpit:
        image: axllent/mailpit:latest
        container_name: ${COMPOSE_PROJECT_NAME}-mailpit
        ports:
            - ${MAILPIT_PORT:-1025}:1025
            - ${MAILPIT_DASHBOARD_PORT:-8025}:8025
    redis:
        image: redis:8.2-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        ports:
            - ${REDIS_PORT:-6379}:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
        volumes:
            - redis-data:/data
    horizon:
        build: .
        image: michaelrushton/${COMPOSE_PROJECT_NAME}/horizon
        container_name: ${COMPOSE_PROJECT_NAME}-horizon
        depends_on:
            redis:
                condition: service_healthy
            db:
                condition: service_healthy
        volumes:
            - ..:/var/www/html
        command: php artisan horizon
volumes:
    db-data:
    db-testing-data:
    redis-data:
